/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as ApiEmailsIndexRouteImport } from './routes/api/emails/index'
import { Route as appWebhooksIndexRouteImport } from './routes/(app)/webhooks/index'
import { Route as appApiIndexRouteImport } from './routes/(app)/api/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as appWebhooksIdRouteImport } from './routes/(app)/webhooks/$id'
import { Route as appEmailsIdRouteImport } from './routes/(app)/emails/$id'
import { Route as appEmailslistsRouteRouteImport } from './routes/(app)/emails/(lists)/route'
import { Route as appEmailslistsIndexRouteImport } from './routes/(app)/emails/(lists)/index'
import { Route as appEmailslistsReceivingRouteImport } from './routes/(app)/emails/(lists)/receiving'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiEmailsIndexRoute = ApiEmailsIndexRouteImport.update({
  id: '/api/emails/',
  path: '/api/emails/',
  getParentRoute: () => rootRouteImport,
} as any)
const appWebhooksIndexRoute = appWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => appRouteRoute,
} as any)
const appApiIndexRoute = appApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appWebhooksIdRoute = appWebhooksIdRouteImport.update({
  id: '/webhooks/$id',
  path: '/webhooks/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appEmailsIdRoute = appEmailsIdRouteImport.update({
  id: '/emails/$id',
  path: '/emails/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appEmailslistsRouteRoute = appEmailslistsRouteRouteImport.update({
  id: '/emails/(lists)',
  path: '/emails',
  getParentRoute: () => appRouteRoute,
} as any)
const appEmailslistsIndexRoute = appEmailslistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appEmailslistsRouteRoute,
} as any)
const appEmailslistsReceivingRoute = appEmailslistsReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => appEmailslistsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/emails': typeof appEmailslistsRouteRouteWithChildren
  '/emails/$id': typeof appEmailsIdRoute
  '/webhooks/$id': typeof appWebhooksIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/': typeof appApiIndexRoute
  '/webhooks/': typeof appWebhooksIndexRoute
  '/api/emails/': typeof ApiEmailsIndexRoute
  '/emails/receiving': typeof appEmailslistsReceivingRoute
  '/emails/': typeof appEmailslistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '/emails/$id': typeof appEmailsIdRoute
  '/webhooks/$id': typeof appWebhooksIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api': typeof appApiIndexRoute
  '/webhooks': typeof appWebhooksIndexRoute
  '/api/emails': typeof ApiEmailsIndexRoute
  '/emails/receiving': typeof appEmailslistsReceivingRoute
  '/emails': typeof appEmailslistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/(app)/emails/(lists)': typeof appEmailslistsRouteRouteWithChildren
  '/(app)/emails/$id': typeof appEmailsIdRoute
  '/(app)/webhooks/$id': typeof appWebhooksIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(app)/api/': typeof appApiIndexRoute
  '/(app)/webhooks/': typeof appWebhooksIndexRoute
  '/api/emails/': typeof ApiEmailsIndexRoute
  '/(app)/emails/(lists)/receiving': typeof appEmailslistsReceivingRoute
  '/(app)/emails/(lists)/': typeof appEmailslistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emails'
    | '/emails/$id'
    | '/webhooks/$id'
    | '/api/trpc/$'
    | '/api/'
    | '/webhooks/'
    | '/api/emails/'
    | '/emails/receiving'
    | '/emails/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emails/$id'
    | '/webhooks/$id'
    | '/api/trpc/$'
    | '/api'
    | '/webhooks'
    | '/api/emails'
    | '/emails/receiving'
    | '/emails'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/'
    | '/(app)/emails/(lists)'
    | '/(app)/emails/$id'
    | '/(app)/webhooks/$id'
    | '/api/trpc/$'
    | '/(app)/api/'
    | '/(app)/webhooks/'
    | '/api/emails/'
    | '/(app)/emails/(lists)/receiving'
    | '/(app)/emails/(lists)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiEmailsIndexRoute: typeof ApiEmailsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/emails/': {
      id: '/api/emails/'
      path: '/api/emails'
      fullPath: '/api/emails/'
      preLoaderRoute: typeof ApiEmailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/webhooks/': {
      id: '/(app)/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof appWebhooksIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/api/': {
      id: '/(app)/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof appApiIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/webhooks/$id': {
      id: '/(app)/webhooks/$id'
      path: '/webhooks/$id'
      fullPath: '/webhooks/$id'
      preLoaderRoute: typeof appWebhooksIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/emails/$id': {
      id: '/(app)/emails/$id'
      path: '/emails/$id'
      fullPath: '/emails/$id'
      preLoaderRoute: typeof appEmailsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/emails/(lists)': {
      id: '/(app)/emails/(lists)'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof appEmailslistsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/emails/(lists)/': {
      id: '/(app)/emails/(lists)/'
      path: '/'
      fullPath: '/emails/'
      preLoaderRoute: typeof appEmailslistsIndexRouteImport
      parentRoute: typeof appEmailslistsRouteRoute
    }
    '/(app)/emails/(lists)/receiving': {
      id: '/(app)/emails/(lists)/receiving'
      path: '/receiving'
      fullPath: '/emails/receiving'
      preLoaderRoute: typeof appEmailslistsReceivingRouteImport
      parentRoute: typeof appEmailslistsRouteRoute
    }
  }
}

interface appEmailslistsRouteRouteChildren {
  appEmailslistsReceivingRoute: typeof appEmailslistsReceivingRoute
  appEmailslistsIndexRoute: typeof appEmailslistsIndexRoute
}

const appEmailslistsRouteRouteChildren: appEmailslistsRouteRouteChildren = {
  appEmailslistsReceivingRoute: appEmailslistsReceivingRoute,
  appEmailslistsIndexRoute: appEmailslistsIndexRoute,
}

const appEmailslistsRouteRouteWithChildren =
  appEmailslistsRouteRoute._addFileChildren(appEmailslistsRouteRouteChildren)

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appEmailslistsRouteRoute: typeof appEmailslistsRouteRouteWithChildren
  appEmailsIdRoute: typeof appEmailsIdRoute
  appWebhooksIdRoute: typeof appWebhooksIdRoute
  appApiIndexRoute: typeof appApiIndexRoute
  appWebhooksIndexRoute: typeof appWebhooksIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appEmailslistsRouteRoute: appEmailslistsRouteRouteWithChildren,
  appEmailsIdRoute: appEmailsIdRoute,
  appWebhooksIdRoute: appWebhooksIdRoute,
  appApiIndexRoute: appApiIndexRoute,
  appWebhooksIndexRoute: appWebhooksIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiEmailsIndexRoute: ApiEmailsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
